### ISSUE TITLE
Static Objects Section in Faster CPython Whats New

### ISSUE THREAD

**Issue by Fidget-Spinner** [Fidget-Spinner/cpython#13]
Static objects section needs help because I'm currently not familiar with all the work involved. More sections may be needed and can be added as necessary.
https://github.com/Fidget-Spinner/cpython/tree/faster_cpython_whatsnew

CC @kumaraditya303 who has volunteered to help. I'm assigning this issue to you. Please open a PR whenever you feel ready :).

**Comment by Fidget-Spinner** [comment]
Frozen imports is done. If there are anything else that's frozen, please feel free to add on. Thanks!

**Comment by kumaraditya303** [comment]
Well, earlier Guido did not exclude the marshaled data so it wasted 300KB worth of space in the binary so as an optimization I removed the marshaled data to save space and directly run the static code objects so it does not exists any more. It was implemented in https://github.com/python/cpython/pull/31074. I have done many more of these deepfreeze optimizations but these are very much implementation details and not worth documenting as what matters for the user is the speedup :)
